version: '3'

services:
  app:
    container_name: app
    build:
      context: node
    networks:
      - node-network
    tty: true
    entrypoint: wait-for db:3306 -t 40 -- sh start.sh
    volumes:
      - ./node:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root  
    networks:
      - node-network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge